### ISSUE TITLE
Duplicate ic_launcher

### ISSUE THREAD

**Issue by tanhauhau** [rspective/PagerDatePicker#4]
Gradle finished with non-zero exit value 1 (ic_launcher.png: error: Duplicate file)

**Comment by polok** [comment]
Hi,

We removed unused drawables from library directory. New version 1.2.0 should be available from maven central in few hours. 

Regards,

**Comment by polok** [comment]
Please, check new version 1.2.0

```
compile 'pl.rspective.pagerdatepicker:pagerdatepicker:1.2.0'
```
