### ISSUE TITLE
unable to resolve thedependency

### ISSUE THREAD

**Issue by abhi9wagadre** [rspective/PagerDatePicker#5]
Error:(26, 13) Failed to resolve: pl.rspective.pagerdatepicker:pagerdatepicker:1.2.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by polok** [comment]
It's still occurs ?

Are you sure that you are not in offline gradle mode in your IDE ?

I double checked, also using this page http://gradleplease.appspot.com/#pagerdatepicker and seems to be fine.

**Comment by abhi9wagadre** [comment]
Sorry for raising the issue again, It is resolved. Thank u !!
