### ISSUE TITLE
unable to resolve the dependency

### ISSUE THREAD

**Issue by abhi9wagadre** [rspective/PagerDatePicker#6]
Error:(27, 13) Failed to resolve: com.github.rspective:PagerDatePicker:release_1.0.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by polok** [comment]
It's still occurs ?

Are you sure that you are not in offline gradle mode in your IDE ?

I double checked, also using this page http://gradleplease.appspot.com/#pagerdatepicker and seems to be fine.

**Comment by abhi9wagadre** [comment]
Yes it got resolved thanku !
