### ISSUE TITLE
unable to build the project

### ISSUE THREAD

**Issue by abhi9wagadre** [rspective/PagerDatePicker#7]
when i try to build the project. it shows up the error.

Error:Execution failed for task ':app:processDebugManifest'.

    Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 10 declared in library [pl.rspective.pagerdatepicker:pagerdatepicker:1.2.0] C:\Users\abhinav\AndroidStudioProjects\materaildesign\app\build\intermediates\exploded-aar\pl.rspective.pagerdatepicker\pagerdatepicker\1.2.0\AndroidManifest.xml
    Suggestion: use tools:overrideLibrary="pl.rspective.pagerdatepicker" to force usage

i am following these steps:https://github.com/rspective/PagerDatePicker

also i want to include the pagerdatepicker in one of my already existing fragment if hamburger menu.
where to put that java code is not mentioned. layout i have edited and colors also.

**Comment by polok** [comment]
Hi,

Regarding the error. The library uses minSdkVersion 10, from the error seems that you have smaller version which is 8. This is a reason why you get this error.

Regards,

**Comment by abhi9wagadre** [comment]
How can I Overcome this issue.?

**Comment by polok** [comment]
Can you set minSdk for your project to 10 instead  of 8 ? 

Only 0.3% of current Android users have such version (https://developer.android.com/about/dashboards/index.html)

**Comment by abhi9wagadre** [comment]
where can I upgrade my minSdk version to 10 in my project ?
Since I am a beginner , I am really having a tough time out here with android studio.
kindly help.

**Comment by polok** [comment]
Go to your project and find '''build.gradle''' file. Then find row which starts from '''minSdkVersion'''

**Comment by abhi9wagadre** [comment]
Also I am not being able to find out where to put that java code of datepicker and datepicker fragement .since step no 2 is optional , i dont want to get into more complexities.
basically from step number 3 to 5 . 
I can share the code of my fragment.java and frament.xml , if you can help .

I am trying to integrate your datepicker into one of my existing fragments of hamburger menu.

**Comment by abhi9wagadre** [comment]
Thanks , i have upgraded my sdk version to 10 . and it can successfully build the project now.
Thanks again.

**Comment by polok** [comment]
Go to sample project where you can check how it was used. The usage is quite simple, you will see whole code there.

**Comment by abhi9wagadre** [comment]
ok , I am trying it. 
Thank you for your time.
If needed , I will raise the issue again.
Thanks,Cheers.
